// <auto-generated />
using System;
using BarberDario.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BarberDario.Api.Migrations
{
    [DbContext(typeof(BarberDarioDbContext))]
    [Migration("20251227215057_AddBookingTracking")]
    partial class AddBookingTracking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BarberDario.Api.Data.Entities.BlockedTimeSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("BlockDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("Reason")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("BlockDate");

                    b.ToTable("BlockedTimeSlots");
                });

            modelBuilder.Entity("BarberDario.Api.Data.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdminNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("BookingDate")
                        .HasColumnType("date");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ConfirmationSentAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomerNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("ReferrerUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReminderSentAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UtmCampaign")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UtmContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UtmMedium")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UtmSource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UtmTerm")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookingDate");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("Status");

                    b.HasIndex("BookingDate", "Status");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("BarberDario.Api.Data.Entities.BusinessHours", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeOnly?>("BreakEndTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("BreakStartTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("CloseTime")
                        .HasColumnType("time");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("bit");

                    b.Property<TimeOnly>("OpenTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("DayOfWeek")
                        .IsUnique();

                    b.ToTable("BusinessHours");

                    b.HasData(
                        new
                        {
                            Id = new Guid("77a854e4-861c-474d-88b1-da40bb0c151b"),
                            CloseTime = new TimeOnly(0, 0, 0),
                            DayOfWeek = 0,
                            IsOpen = false,
                            OpenTime = new TimeOnly(0, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("e0c4734d-0c8c-49ed-8fa3-ad254849a5e4"),
                            CloseTime = new TimeOnly(18, 0, 0),
                            DayOfWeek = 1,
                            IsOpen = true,
                            OpenTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("d9f4da3e-9548-455c-9f54-9620cd9355ca"),
                            CloseTime = new TimeOnly(18, 0, 0),
                            DayOfWeek = 2,
                            IsOpen = true,
                            OpenTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("43cf2ba7-97ce-401c-a44d-4a4e978dacf1"),
                            CloseTime = new TimeOnly(18, 0, 0),
                            DayOfWeek = 3,
                            IsOpen = true,
                            OpenTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("d5396705-fde0-47c1-997f-3a410940fa70"),
                            CloseTime = new TimeOnly(20, 0, 0),
                            DayOfWeek = 4,
                            IsOpen = true,
                            OpenTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("f2a8b7c9-e383-4d6b-aeca-f385544a0a30"),
                            CloseTime = new TimeOnly(18, 0, 0),
                            DayOfWeek = 5,
                            IsOpen = true,
                            OpenTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("5c96e3ad-8ee6-4044-8b49-9afae24e1118"),
                            CloseTime = new TimeOnly(16, 0, 0),
                            DayOfWeek = 6,
                            IsOpen = true,
                            OpenTime = new TimeOnly(9, 0, 0)
                        });
                });

            modelBuilder.Entity("BarberDario.Api.Data.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastVisit")
                        .HasColumnType("datetime2");

                    b.Property<int>("NoShowCount")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TotalBookings")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Phone");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("BarberDario.Api.Data.Entities.EmailLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipientEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("EmailType");

                    b.ToTable("EmailLogs");
                });

            modelBuilder.Entity("BarberDario.Api.Data.Entities.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2025, 12, 27, 21, 50, 57, 557, DateTimeKind.Utc).AddTicks(7300),
                            Description = "Klassischer Herrenhaarschnitt mit Styling",
                            DisplayOrder = 1,
                            DurationMinutes = 30,
                            IsActive = true,
                            Name = "Herrenschnitt",
                            Price = 35.00m,
                            UpdatedAt = new DateTime(2025, 12, 27, 21, 50, 57, 557, DateTimeKind.Utc).AddTicks(7300)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2025, 12, 27, 21, 50, 57, 557, DateTimeKind.Utc).AddTicks(7330),
                            Description = "Professionelles Bart-Trimming und Konturenschneiden",
                            DisplayOrder = 2,
                            DurationMinutes = 20,
                            IsActive = true,
                            Name = "Bart Trimmen",
                            Price = 20.00m,
                            UpdatedAt = new DateTime(2025, 12, 27, 21, 50, 57, 557, DateTimeKind.Utc).AddTicks(7330)
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2025, 12, 27, 21, 50, 57, 557, DateTimeKind.Utc).AddTicks(7330),
                            Description = "Haarschnitt + Bart Trimmen",
                            DisplayOrder = 3,
                            DurationMinutes = 50,
                            IsActive = true,
                            Name = "Komplettpaket",
                            Price = 50.00m,
                            UpdatedAt = new DateTime(2025, 12, 27, 21, 50, 57, 557, DateTimeKind.Utc).AddTicks(7330)
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2025, 12, 27, 21, 50, 57, 557, DateTimeKind.Utc).AddTicks(7340),
                            Description = "Haarschnitt für Kinder bis 12 Jahre",
                            DisplayOrder = 4,
                            DurationMinutes = 30,
                            IsActive = true,
                            Name = "Kinder Haarschnitt",
                            Price = 25.00m,
                            UpdatedAt = new DateTime(2025, 12, 27, 21, 50, 57, 557, DateTimeKind.Utc).AddTicks(7340)
                        });
                });

            modelBuilder.Entity("BarberDario.Api.Data.Entities.Setting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            Key = "BOOKING_INTERVAL_MINUTES",
                            Description = "Zeitintervall für Buchungen in Minuten",
                            UpdatedAt = new DateTime(2025, 12, 27, 21, 50, 57, 557, DateTimeKind.Utc).AddTicks(7520),
                            Value = "15"
                        },
                        new
                        {
                            Key = "MAX_ADVANCE_BOOKING_DAYS",
                            Description = "Wie viele Tage im Voraus kann gebucht werden",
                            UpdatedAt = new DateTime(2025, 12, 27, 21, 50, 57, 557, DateTimeKind.Utc).AddTicks(7520),
                            Value = "60"
                        },
                        new
                        {
                            Key = "MIN_ADVANCE_BOOKING_HOURS",
                            Description = "Mindestvorlauf für Buchungen in Stunden",
                            UpdatedAt = new DateTime(2025, 12, 27, 21, 50, 57, 557, DateTimeKind.Utc).AddTicks(7520),
                            Value = "24"
                        },
                        new
                        {
                            Key = "REMINDER_HOURS_BEFORE",
                            Description = "Wann vor dem Termin wird die Erinnerung gesendet (Stunden)",
                            UpdatedAt = new DateTime(2025, 12, 27, 21, 50, 57, 557, DateTimeKind.Utc).AddTicks(7520),
                            Value = "24"
                        },
                        new
                        {
                            Key = "ADMIN_EMAIL",
                            Description = "Admin Email-Adresse",
                            UpdatedAt = new DateTime(2025, 12, 27, 21, 50, 57, 557, DateTimeKind.Utc).AddTicks(7520),
                            Value = "dario@barberdario.com"
                        },
                        new
                        {
                            Key = "BUSINESS_NAME",
                            Description = "Name des Geschäfts",
                            UpdatedAt = new DateTime(2025, 12, 27, 21, 50, 57, 557, DateTimeKind.Utc).AddTicks(7530),
                            Value = "Barber Dario"
                        },
                        new
                        {
                            Key = "BUSINESS_ADDRESS",
                            Description = "Geschäftsadresse",
                            UpdatedAt = new DateTime(2025, 12, 27, 21, 50, 57, 557, DateTimeKind.Utc).AddTicks(7530),
                            Value = "Berliner Allee 43, 40212 Düsseldorf"
                        },
                        new
                        {
                            Key = "TIMEZONE",
                            Description = "Zeitzone des Geschäfts",
                            UpdatedAt = new DateTime(2025, 12, 27, 21, 50, 57, 557, DateTimeKind.Utc).AddTicks(7530),
                            Value = "Europe/Berlin"
                        });
                });

            modelBuilder.Entity("BarberDario.Api.Data.Entities.Booking", b =>
                {
                    b.HasOne("BarberDario.Api.Data.Entities.Customer", "Customer")
                        .WithMany("Bookings")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BarberDario.Api.Data.Entities.Service", "Service")
                        .WithMany("Bookings")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("BarberDario.Api.Data.Entities.EmailLog", b =>
                {
                    b.HasOne("BarberDario.Api.Data.Entities.Booking", "Booking")
                        .WithMany("EmailLogs")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("BarberDario.Api.Data.Entities.Booking", b =>
                {
                    b.Navigation("EmailLogs");
                });

            modelBuilder.Entity("BarberDario.Api.Data.Entities.Customer", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("BarberDario.Api.Data.Entities.Service", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
